#!/bin/bash
python vrpSolverV2.py ga1 > Tabu.txt
python vrpSolverV2.py ga2 >> Tabu.txt
python vrpSolverV2.py ga3 >> Tabu.txt
python vrpSolverV2.py ga4 >> Tabu.txt
python vrpSolverV2.py gb1 >> Tabu.txt
python vrpSolverV2.py gb2 >> Tabu.txt
python vrpSolverV2.py gb3 >> Tabu.txt
python vrpSolverV2.py gc1 >> Tabu.txt
python vrpSolverV2.py gc2 >> Tabu.txt
python vrpSolverV2.py gc3 >> Tabu.txt
python vrpSolverV2.py gc4 >> Tabu.txt
python vrpSolverV2.py gd1 >> Tabu.txt
python vrpSolverV2.py gd2 >> Tabu.txt
python vrpSolverV2.py gd3 >> Tabu.txt
python vrpSolverV2.py gd4 >> Tabu.txt
python vrpSolverV2.py ge1 >> Tabu.txt
python vrpSolverV2.py ge2 >> Tabu.txt
python vrpSolverV2.py ge3 >> Tabu.txt
python vrpSolverV2.py gf1 >> Tabu.txt
python vrpSolverV2.py gf2 >> Tabu.txt
python vrpSolverV2.py gf3 >> Tabu.txt
python vrpSolverV2.py gf4 >> Tabu.txt
python vrpSolverV2.py gg1 >> Tabu.txt
python vrpSolverV2.py gg2 >> Tabu.txt
python vrpSolverV2.py gg3 >> Tabu.txt
python vrpSolverV2.py gg4 >> Tabu.txt
python vrpSolverV2.py gg5 >> Tabu.txt
python vrpSolverV2.py gg6 >> Tabu.txt
python vrpSolverV2.py gh1 >> Tabu.txt
python vrpSolverV2.py gh2 >> Tabu.txt
python vrpSolverV2.py gh3 >> Tabu.txt
python vrpSolverV2.py gh4 >> Tabu.txt
python vrpSolverV2.py gh5 >> Tabu.txt
python vrpSolverV2.py gh6 >> Tabu.txt
python vrpSolverV2.py gi1 >> Tabu.txt
python vrpSolverV2.py gi2 >> Tabu.txt
python vrpSolverV2.py gi3 >> Tabu.txt
python vrpSolverV2.py gi4 >> Tabu.txt
python vrpSolverV2.py gi5 >> Tabu.txt
python vrpSolverV2.py gj1 >> Tabu.txt
python vrpSolverV2.py gj2 >> Tabu.txt
python vrpSolverV2.py gj3 >> Tabu.txt
python vrpSolverV2.py gj4 >> Tabu.txt
python vrpSolverV2.py gk1 >> Tabu.txt
python vrpSolverV2.py gk2 >> Tabu.txt
python vrpSolverV2.py gk3 >> Tabu.txt
python vrpSolverV2.py gk4 >> Tabu.txt
python vrpSolverV2.py gl1 >> Tabu.txt
python vrpSolverV2.py gl2 >> Tabu.txt
python vrpSolverV2.py gl3 >> Tabu.txt
python vrpSolverV2.py gl4 >> Tabu.txt
python vrpSolverV2.py gl5 >> Tabu.txt
python vrpSolverV2.py gm1 >> Tabu.txt
python vrpSolverV2.py gm2 >> Tabu.txt
python vrpSolverV2.py gm3 >> Tabu.txt
python vrpSolverV2.py gm4 >> Tabu.txt
python vrpSolverV2.py gn1 >> Tabu.txt
python vrpSolverV2.py gn2 >> Tabu.txt
python vrpSolverV2.py gn3 >> Tabu.txt
python vrpSolverV2.py gn4 >> Tabu.txt
python vrpSolverV2.py gn5 >> Tabu.txt
python vrpSolverV2.py gn6 >> Tabu.txt