#!/bin/bash
python vrpSolverV2.py ga1 > Tabu.txt
python vrpSolverV2.py ga2 >> Tabu.txt
python vrpSolverV2.py ga3 >> Tabu.txt
python vrpSolverV2.py ga4 >> Tabu.txt
python vrpSolverV2.py gb1 >> Tabu.txt
python vrpSolverV2.py gb2 >> Tabu.txt
python vrpSolverV2.py gb3 >> Tabu.txt
python vrpSolverV2.py gc1 >> Tabu.txt
python vrpSolverV2.py gc2 >> Tabu.txt
python vrpSolverV2.py gc3 >> Tabu.txt
python vrpSolverV2.py gc4 >> Tabu.txt
python vrpSolverV2.py gd1 >> Tabu.txt
python vrpSolverV2.py gd2 >> Tabu.txt
python vrpSolverV2.py gd3 >> Tabu.txt
python vrpSolverV2.py gd4 >> Tabu.txt
python vrpSolverV2.py ge1 >> Tabu.txt
python vrpSolverV2.py ge2 >> Tabu.txt
python vrpSolverV2.py ge3 >> Tabu.txt
python vrpSolverV2.py gf1 >> Tabu.txt
python vrpSolverV2.py gf2 >> Tabu.txt
python vrpSolverV2.py gf3 >> Tabu.txt
python vrpSolverV2.py gf4 >> Tabu.txt
python vrpSolverV2.py gg1 >> Tabu.txt
python vrpSolverV2.py gg2 >> Tabu.txt
python vrpSolverV2.py gg3 >> Tabu.txt
python vrpSolverV2.py gg4 >> Tabu.txt
python vrpSolverV2.py gg5 >> Tabu.txt
python vrpSolverV2.py gg6 >> Tabu.txt