#!/bin/bash
echo "Mejor conocido,ILS encontrado,Tiempo ils,% error ils,Genetico encontrado,Tiempo gen,% error gen" > soluciones.csv
python3 Vrp.py GA1 3 >> soluciones.csv
python3 Vrp.py GA2 3 >> soluciones.csv
python3 Vrp.py GA3 3 >> soluciones.csv
python3 Vrp.py GA4 3 >> soluciones.csv
python3 Vrp.py GB1 3 >> soluciones.csv
python3 Vrp.py GB2 3 >> soluciones.csv
python3 Vrp.py GB3 3 >> soluciones.csv
python3 Vrp.py GC1 3 >> soluciones.csv
python3 Vrp.py GC2 3 >> soluciones.csv
python3 Vrp.py GC3 3 >> soluciones.csv
python3 Vrp.py GC4 3 >> soluciones.csv
python3 Vrp.py GD1 3 >> soluciones.csv
python3 Vrp.py GD2 3 >> soluciones.csv
python3 Vrp.py GD3 3 >> soluciones.csv
python3 Vrp.py GD4 3 >> soluciones.csv
python3 Vrp.py GE1 3 >> soluciones.csv
python3 Vrp.py GE2 3 >> soluciones.csv
python3 Vrp.py GE3 3 >> soluciones.csv
python3 Vrp.py GF1 3 >> soluciones.csv
python3 Vrp.py GF2 3 >> soluciones.csv
python3 Vrp.py GF3 3 >> soluciones.csv
python3 Vrp.py GF4 3 >> soluciones.csv
python3 Vrp.py GG1 3 >> soluciones.csv
python3 Vrp.py GG2 3 >> soluciones.csv
python3 Vrp.py GG3 3 >> soluciones.csv
python3 Vrp.py GG4 3 >> soluciones.csv
python3 Vrp.py GG5 3 >> soluciones.csv
python3 Vrp.py GG6 3 >> soluciones.csv
